const styles = {
    body:{
        backgroundColor:'#0D698B',
        height:'100vh',
        width:'100%',
        display:'flex',
        flexDirection:'column',
    },
    titleArea: {
        display:'flex',
        flexDirection:'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    title:{
        color:'#FFFFFF',
        marginLeft:16,
        fontSize:30,
    },
    tabs:{
        width:'100%',
        display: 'flex',
        flexDirection:'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop:20,
        marginLeft:16,
        marginRight:16,
    },
    tabActive:{
        width:'50%',
        border:'none',
        padding:'8px 16px',
        borderTopLeftRadius:5,
        borderTopRightRadius:5,
        backgroundColor:'#F2F1E8',
        fontSize:14,
        fontWeight:'bold',
        color:'#050533',
        marginBottom:0,
        paddingBottom:12,

    },
    tabInactive:{
        backgroundColor:'transparent',
        width:'50%',
        border:'none',
        padding:'8px 16px',
        fontSize:14,
        fontWeight:'bold',
        color:'#F2F1E8',
        paddingBottom:8,

    },
    tabsSmall:{
        width:'100%',
        display: 'flex',
        flexDirection:'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop:20,
        marginLeft:8,
        marginRight:0,
    },
    tabActiveSmall:{
        width:'33%',
        border:'none',
        padding:'8px 16px',
        borderTopLeftRadius:5,
        borderTopRightRadius:5,
        backgroundColor:'#F2F1E8',
        fontSize:12,
        fontWeight:'bold',
        color:'#050533',
        marginBottom:0,
        paddingBottom:8,
    },
    tabInactiveSmall:{
        backgroundColor:'transparent',
        width:'33%',
        border:'none',
        padding:'8px 16px',
        fontSize:12,
        fontWeight:'bold',
        color:'#F2F1E8',
    },
    environments:{
        height:'100%',
        backgroundColor:'#F2F1E8',
        display: 'flex',
        flexDirection:'column',
        alignItems: 'center',
        paddingTop:30,
    }
}

export default styles;